objs = iter([23, 78, True, 'hello', [123, 433]])
print(next(objs))
print(next(objs))
print(next(objs))
print(next(objs))
print()
objs = iter([23, 78, True, 'hello'])
print(next(objs))
print(next(objs))
print(next(objs))
print(next(objs))
print(next(objs))
